leads/urls.py
from django.urls import path
from.views import  lead_create, lead_detail, lead_list,lead_update,lead_delete,LeadListView,LeadDetailView,LeadCreateView,LeadUpdateView,LeadDeleteView,CategoryList

app_name="leads"
urlpatterns=[
path('',LeadListView.as_view(),name="lead_list"),
path('<int:pk>/',LeadDetailView.as_view(),name="lead_detail"),
path('create/',LeadCreateView.as_view(),name="lead_create"),
path('<int:pk>/update',LeadUpdateView.as_view(),name="lead_update"),
path('<int:pk>/delete',LeadDeleteView.as_view(),name="lead_delete"),
path('categories/',CategoryList.as_view(),name="categories"),









]

management/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView,PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView
from leads.views import landing_page,LandingPageView,SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(),name="landing_page"),

    path('leads/', include('leads.urls',namespace='leads')),
    path('agents/', include('agents.urls',namespace='agents')),

    path('login/', LoginView.as_view(),name="login"),
    path('reset_password/', PasswordResetView.as_view(),name="password_reset"),
    path('password-reset-done/', PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),name="password_reset_complete"),




    path('signup/', SignUpView.as_view(),name="signup"),

    path('logout/', LogoutView.as_view(),name="logout"),


]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

leads/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey, OneToOneField
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    is_organisor=models.BooleanField(default=True)
    is_agent=models.BooleanField(default=False)




class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Lead(models.Model):
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    age=models.IntegerField(default=0)
    organisation=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    agent=models.ForeignKey("Agent", null=True,blank=True,on_delete=models.SET_NULL)
    category=models.ForeignKey("Category",on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"



class Category(models.Model):
    name=models.CharField(max_length=30)
    organisation=models.ForeignKey(UserProfile,on_delete=models.CASCADE)

    def __str__(self):
        return self.name           
   
class Agent(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    organisation=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    def __str__(self):
        return self.user.email


def post_user_created_signal(sender,instance,created,**kwargs):
    print(instance)
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal,sender=User)            

leads/forms.py
from django import forms
from django.forms import fields
from.models import Lead
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model
User=get_user_model()


from leads.models import Lead

class LeadForm(forms.Form):
    first_name=forms.CharField(max_length=30)
    last_name=forms.CharField(max_length=30)
    age=forms.IntegerField(min_value=0)


class LeadModelForm(forms.ModelForm):
    class Meta:
        model=Lead
        fields="__all__"

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=User
        fields=("username",)
        field_classes={"username":UsernameField}       
      

leads/views.py
from django.core.mail import message, send_mail 
from django.shortcuts import render,redirect
from django.views.generic.edit import UpdateView
from.models import Lead,Agent
from.forms import LeadForm,LeadModelForm
from django.views import generic
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from leads.forms import CustomUserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganisorandLoginRequiredMixin
from .models import Category
# Create your views here.




class SignUpView(generic.CreateView):
    template_name='registration/signup.html'
    form_class=CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(generic.TemplateView):
    template_name='landing.html'

def landing_page(request):
    return render(request,'landing.html')




class LeadListView(LoginRequiredMixin,generic.ListView):
    template_name='leads/lead_list.html'
    context_object_name="leads"

    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)
            queryset=queryset.filter(agent__user=user)
        return queryset




def lead_list(request):
    leads=Lead.objects.all()
    return render(request,'leads/lead_list.html',context={'leads':leads})



class LeadDetailView(OrganisorandLoginRequiredMixin,generic.DetailView):
    template_name='leads/lead_detail.html'
    context_object_name="lead"
    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)
            queryset=queryset.filter(agent__user=user)
        return queryset






def lead_detail(request,pk):
    lead=Lead.objects.get(id=pk)
    return render(request,'leads/lead_detail.html',context={'lead':lead})





class LeadCreateView(OrganisorandLoginRequiredMixin,generic.CreateView):
    template_name='leads/lead_create.html'
    form_class=LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead_list")

    def form_valid(self, form):
        send_mail(
        subject="Lead ugurla yaradildi",message="Yeni Leadi gormek ucun site'i tiklayin",from_email="test@test.com",recipient_list=["test2@test2.com"]

        )
        return super(LeadCreateView,self).form_valid(form)    

def lead_create(request):
    form=LeadModelForm()
    if request.method=="POST":
        form=LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('leads:lead_list')
            
    return render(request,'leads/lead_create.html',context={'form':form})   



class LeadUpdateView(OrganisorandLoginRequiredMixin,generic.UpdateView):
    template_name='leads/lead_update.html'
    form_class=LeadModelForm
    def get_queryset(self):
        user=self.request.user
       
    
        return Lead.objects.filter(organisation=user.userprofile)


    def get_success_url(self):
        return reverse("leads:lead_list")



def lead_update(request,pk):
    lead=Lead.objects.get(id=pk)
    form=LeadModelForm(instance=lead)
    if request.method=="POST":
        form=LeadModelForm(request.POST,instance=lead)
        if form.is_valid():
            form.save()
            return redirect('leads:lead_list')
    return render(request,'leads/lead_update.html',context={'form':form,'lead':lead})   




class LeadDeleteView(OrganisorandLoginRequiredMixin,generic.DeleteView):
    template_name='leads/lead_delete.html'  
    def get_queryset(self):
        user=self.request.user
       
    
        return Lead.objects.filter(organisation=user.userprofile)
 
    def get_success_url(self):
        return reverse("leads:lead_list")    

def lead_delete(request,pk):
    lead=Lead.objects.get(id=pk)
    lead.delete()
    return redirect('leads:lead_list')
    
  
class CategoryList(LoginRequiredMixin,generic.ListView):
    template_name="leads/category_list.html"  
    context_object_name='category'
    
    def get_queryset(self):
        user=self.request.user
        if user.is_organisor:
            queryset=Category.objects.filter(organisation=user.userprofile)
        else:
            queryset=Category.objects.filter(organisation=user.agent.organisation)
        return queryset


    def get_context_data(self, **kwargs):
        context=super(CategoryList,self).get_context_data(**kwargs)   
        user=self.request.user
        if user.is_organisor:
            queryset=Lead.objects.filter(organisation=user.profile)
        else:
            queryset=Lead.objetcs.filter(organisation=user.agent.organisation)    
        context.update({"unassigned_lead_count":queryset.filter(category__isnull=True).count()})    


# def lead_create(request):
#     form=LeadForm()
#     if request.method=="POST":
#         form=LeadForm(request.POST)
#         if form.is_valid():
#             first_name=form.cleaned_data['first_name']
#             last_name=form.cleaned_data['last_name']
#             age=form.cleaned_data['age']
#             agent=Agent.objects.first()
#             Lead.objects.create(first_name=first_name,last_name=last_name,age=age,agent=agent)
#             return redirect('leads:lead_list')
            
#     return render(request,'leads/lead_create.html',context={'form':form})         
        

leads/templates/leads/category_list.html
{%extends 'base.html'%}{%block content%}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">This categorie segmet leads</p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">lead sayi</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="px-4 py-3">Unassigned</td>
                        <td class="px-4 py-3">{{unassigned_lead_count}}</td>

                    </tr>
                    {%for category in category_list%}
                    <tr>
                        <td class="px-4 py-3">{{category.name}}</td>
                        <td class="px-4 py-3">Todo count</td>

                    </tr>
                    {%endfor%}

                </tbody>
            </table>
        </div>

    </div>
</section> {%endblock content}

leads/templates/leads/lead_create.html
 {% extends 'base.html' %}{% load tailwind_filters %} {% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-t border-gray-200 mt-5"><a href="{%url 'leads:lead_list' %}" class="hover:text-blue-500"><a href="{% url 'leads:lead_list' %}">Back to previous page</a></a>
    </div>
    <form action="" method="post">
        {% csrf_token %} {{form|crispy }}
        <button type="submit" class="w-full bg-blue-500 hover:bg-gray-500 px-3 py-1 rounded-md">Submit</button>



    </form>
    <div class="py-5 border-t border-gray-200 mt-5"><a href="{%url 'password_reset' %}">Passwordu unutmusunuz?</a></div>

</div> {% endblock content%}

leads/templates/leads/lead_delete.html
{% extends 'base.html'%} {%block content %}<a href="{% url 'leads:lead_list' %}">Back to previous page</a>
<hr>
<h1>Silmək istədiyinizə əminsiz?</h1>
<form action="" method="post">
    {% csrf_token%} {{form.as_p}}
    <button type="submit">Submit</button>

</form>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html'%} {%block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name}} {{ lead.last_name}}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:lead_detail'  lead.id%}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1 ">Detail</a>
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 ">Reviews</a>
                    <a href="{% url 'leads:lead_update' lead.id%} " class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 ">Update</a>
                </div>
                <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin
                    listicle pour-over, neutra jean.</p>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Yaş</span>
                    <span class="ml-auto text-gray-900">{{lead.age}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Location</span>
                    <span class="ml-auto text-gray-900">Dummy location</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Əlaqə nömrəsi</span>
                    <span class="ml-auto text-gray-900">+994706006546</span>
                </div>
                <div class="flex">
                    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
                    <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
                </div>
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
        </div>
    </div>
</section>

{%endblock content %}

leads/templates/leads/lead_list.html
{% extends 'base.html'%} {%block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Leads</h1>
            </div>
            {%if request.user.is_organisor%}
            <div>
                <a href="{% url 'leads:lead_create'%}" class="text-gray-500 hover:text-red-700">Yeni lead yaradin</a>
            </div>
            {%endif%}
        </div>
        <a href="{%url 'leads:lead_create' %}">in order to create order click this link</a>

        <div class="flex flex-wrap -m-4">
            <hr> {% for lead in leads%}
            <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
                    </div>
                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}} {{lead.last_name}}</h2>
                        <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
                        <a href="{%url 'leads:lead_detail' lead.id %}" lass="mt-3 text-indigo-500 inline-flex items-center">Göz at
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
                    </div>
                </div>
            </div>
            {% endfor %}


        </div>
    </div>
</section>
{%endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}{% load tailwind_filters %} {%block content%}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name}} {{ lead.last_name}}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:lead_detail'  lead.id%}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 ">Detail</a>
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 ">Reviews</a>
                    <a href="{% url 'leads:lead_update' lead.id%} " class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1 ">Update</a>
                </div>
                <form action=" " method="post">
                    {% csrf_token%} {{form.crispy}}
                    <button type="submit" class="w-full bg-blue-500 hover:bg-gray-500 px-3 py-1 rounded-md">Update</button>

                </form>
                <a href="{% url 'leads:lead_delete' lead.id%} " class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded ">Sil</a>

            </div>
            <img alt="ecommerce " class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded " src="https://dummyimage.com/400x400 ">
        </div>
    </div>
</section>



{% endblock content%}